### ISSUE TITLE
Делать длинные list comprehensions допустимо?

### ISSUE THREAD

**Issue by ggguser** [Lagunov-PRO/Playground#1]
@coursar
Что скажите насчёт такого длинного comprehension (как это по-русски, кстати)? 
Второй вопрос: можно ли сравнить два списка на совпадения не создавая копии с lowercase элементами?

https://github.com/Lagunov-PRO/Playground/blob/d4dd2cf325a19df4292548835137940714776a97/crash_course/5-10_usernames.py#L13-L22

**Comment by coursar** [comment]
Нежелательно, т.к. ухудшает читабельность
