### ISSUE TITLE
Java воспринимает словарь как объект и не печатает.

### ISSUE THREAD

**Issue by ggguser** [Lagunov-PRO/Playground#3]
Создаю объект, вызываю метод, получаю от него словарь. Пытаюсь распечатать, но Java говорит, что это не словарь, а объект.
![image](https://user-images.githubusercontent.com/47136928/55391957-02d20980-5543-11e9-86df-00b136892bed.png)
Создание переменной, вызов метода:
https://github.com/Lagunov-PRO/Playground/blob/4f233a17f797953ccda10d1c9cee3c764462ab29/07_selenide/DeleteUsersBatch.java#L29-L32
Создание словаря в методе:
https://github.com/Lagunov-PRO/Playground/blob/199c0631b248d53a0a3513c79a0b4ea9e6669379/07_selenide/DeleteUsersBatch.java#L52-L54
Возвращение словаря из метода:
https://github.com/Lagunov-PRO/Playground/blob/199c0631b248d53a0a3513c79a0b4ea9e6669379/07_selenide/DeleteUsersBatch.java#L111

**Comment by coursar** [comment]
Alt + Insert -> toString (в IDEA)
