### ISSUE TITLE
Передаю словарь дальше, говорит, что ждёт объект.

### ISSUE THREAD

**Issue by ggguser** [Lagunov-PRO/Playground#4]
![image](https://user-images.githubusercontent.com/47136928/55403176-edb6a400-555d-11e9-8bd9-3e79d1e1df6d.png)

https://github.com/Lagunov-PRO/Playground/blob/d0becf5343286732d535415d2fd6fec10849eca1/07_selenide/DeleteUsersBatch.java#L26-L40

**Comment by coursar** [comment]
Тогда при объявлении вы должны указать, что будут храниться строки (29 стр.):
```java
     Map<String, String> newUsersLoginsPasswords = getAllNewUsersLoginsPasswords(); 
```
